services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bythen-blog-platform-api
    container_name: bythen-blog-platform-api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - bythen-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: mysql-bythen
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p\"${MYSQL_ROOT_PASSWORD}\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - bythen-network

volumes:
  go-build-cache:
  go-mod-cache:
  mysql_data:

networks:
  bythen-network:
    external: true